### ISSUE TITLE
morning session peer-2-peer code review

### ISSUE THREAD

**Issue by degisew** [elfin-git/To-Do-List#4]
Hello @elfin-git 
 Great job so far 👏  👏 

there are  still some issues in your repo

- kindly, remove all the dead codes from your code base.
- kindly, try to give a proper indentation.

**Comment by mahdimahdawi** [comment]
You did a great job 👍✔:
- Still you can implement some optional changes:
- it seems that you didn't used any font family to give style to your text, using of appropriate font family shows you professionalism.

**Comment by TracyMuso** [comment]
Hi team! I implemented all the changes. Thanks! btw, I did use a font family, it just looks really simple, that's how I wanted it :)
